name: Test Report Generation
on: workflow_dispatch
jobs:
  test-report-gen:
    outputs:
      reportFileName: ${{steps.running-test.outputs.reportFileName}}

    runs-on: ubuntu-latest
    steps:
      - name: Test-artifact-Name
        id: step-1
        run: echo "reportFileName=$(date +"%F")-test-report.json" >> $GITHUB_OUTPUT
      - name: Print File Name
        run: echo ${{steps.step-1.outputs.reportFileName}}
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        id: running-test
        run: npm run test
      - name: Upload Test File
        # if: failure() && steps.running-test.outcome == 'failure'
        if: always()
        # always() command executes irrespective of the failure from the steps above. and the test report file will be downloaded as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{steps.step-1.outputs.reportFileName}}
          path: test-reports.json
  deploy-report:
    needs: test-report-gen
    runs-on: ubuntu-latest
    steps:
      - name: Dowload test report
        uses: actions/download-artifact@v3
        with:
          name: ${{needs.test-report-gen.outputs.reportFileName}}
      - name: List files
        run: ls
