name: Test Report Generation
on: workflow_dispatch
jobs:
  test-report-gen:
    outputs:
      reportDate: ${{steps.running-test.outputs.reportDate}}

    runs-on: ubuntu-latest
    steps:
      - name: Test-artifact-Name
        id: step-1
        run: echo "reportDate=$(date +"%F")" >> $GITHUB_OUTPUT
      - name: Print File Name
        run: echo ${{steps.step-1.outputs.reportDate}}
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        id: running-test
        run: npm run test
      - name: Upload Test File
        # if: failure() && steps.running-test.outcome == 'failure'
        if: always()
        # always() command executes irrespective of the failure from the steps above. and the test report file will be downloaded as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{steps.running-test.outputs.reportDate}}-test-report.json
          path: test-reports.json
