name: Test Report Generation
on: workflow_dispatch
jobs:
  test-report-gen:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        id: running-test
        run: npm run test
      - name: Upload Test File
        if: failure() && steps.running-test.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-reports.json
